### ISSUE TITLE
Utilisation des rectifications orthographiques du français de 1990

### ISSUE THREAD

**Issue by rspt** [vuejs-fr/vuejs.org#100]
Bonjour à vous,

Lors de mes relectures orthographiques (principalement dans [nuxt](https://github.com/vuejs-fr/nuxt)), j'ai pu apercevoir un mélange entre l'ancienne et la nouvelle graphie francophone.

Ma question est la suivante: quel type de graphie utilisons-nous?

Mon point de vue personnel est d'utiliser la graphie rectifiée afin de suivre l'évolution du français.

[En savoir plus sur les rectifications orthographiques.](https://fr.wikipedia.org/wiki/Rectifications_orthographiques_du_fran%C3%A7ais_en_1990)

**Comment by Haeresis** [comment]
Nous serions ravi d'accueillir tes PR avec les termes rectifiés. De mémoire je sais déjà qu'on utilise « évènement » comme graphie rectifiée. On essait d'aller dans ce sens.

J'approuve 👍

**Comment by rspt** [comment]
Top pour moi!

Est-ce que je commence déjà à passer en revue le repo vuejs.org avec la nouvelle graphie ou attendons-nous la validation d'autres personnes?

**Comment by Haeresis** [comment]
Oui on a déjà commencé dans se sens, donc je pense pas qu'on reviennent en arrière.

**Comment by rspt** [comment]
Je clos l'issue dans ce cas. On la rouvrira en cas de choix contraire.
