### ISSUE TITLE
Relecture de la version 2.5

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#106]
La 2.5 de Vue.js est sortie et la doc a bougée en conséquence.

J'aurais besoin de vos relectures sur ce commit. Laissez des commentaires, je changerais rétro-activement ;)

Je veux bien l'œil de @sylvainpolletvillard, @Kocal, @forresst et pourquoi pas @rspt ;)

Le commit en question : 
— https://github.com/vuejs-fr/vuejs.org/commit/08185ae3ae2b5a29c4c45140b6d741e8df4b7573

**Comment by rspt** [comment]
Je suis passé en vitesse la-dessus :)

**Comment by sylvainpolletvillard** [comment]
J'ai aussi fair une relecture. Les commentaires de commit ne sont pas le format idéal pour une code review à plusieurs, ce serait mieux de faire une pull request la prochaine fois

**Comment by Haeresis** [comment]
C'était prévu, j'y suis pas encore arrivé. La prochaine fois j'espère.

(Pour la petite histoire j'ai fait hier et aujourd'hui une

**Comment by Haeresis** [comment]
La review de @haeresis
— https://github.com/vuejs-fr/vuejs.org/commit/5493d55460c934b99fc32b4fe999512eb7748f84

**Comment by sylvainpolletvillard** [comment]
Curieux, tu as dû pointer vers le mauvais upstream je pense s'il n'a trouvé aucune différence.

**Comment by Haeresis** [comment]
Oui j'ai du me chier dessus. Je vais y arriver la prochaine fois !

**Comment by Haeresis** [comment]
La review de @sylvainpolletvillard 
— https://github.com/vuejs-fr/vuejs.org/commit/0ba6720e05b2c230f8ffff2d03ffcf6da27b17d2

**Comment by Haeresis** [comment]
Les retours de @rspt 
— https://github.com/vuejs-fr/vuejs.org/commit/7ab8aa2252b793802b5c1ea0ebaf47d8ceae551e

**Comment by Haeresis** [comment]
Merci à vous !
