### ISSUE TITLE
Livre sur Vue 2

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#16]
Je suis tombé la dessus today. 

https://leanpub.com/vuejs2-french/c/MajestyOfVuejs2Discount

Je sais pas dans quelle mesure ce livre peut aider ou non, mais je note que les auteurs on appelé la "version Standalone" la "version Autonome"

**Comment by sylvainpolletvillard** [comment]
Je n'arrive pas à trouver qui est le traducteur. Son expérience nous serait très utile.

**Comment by nyl-auster** [comment]
En effet, c'est dommage de se reposer les mêmes questions, on aurait même intérêt à s'aligner dessus sauf si elles sont déconnantes. Ils sont plusieurs traducteurs
https://twitter.com/hootlex
https://twitter.com/n_nacim?lang=fr
https://twitter.com/kostaskafcas?lang=fr

**Comment by nyl-auster** [comment]
Je suis en train de lire l'extrait, y'a pas eu de relecture visiblement, il reste pas mal de typos, coquillent, espaces manquants. Ca ne présage pas de la qualité intrinsèque mais ça donne direct envie d'arrêter de lire .

**Comment by Haeresis** [comment]
Nous établirons donc nos conventions « officielles » puisque nous sommes Vuejs-FR. Libre aux auteurs de se réaligner sur notre documentation officiel à l'avenir ou de venir participer à ses adoptions ici.
