### ISSUE TITLE
[Suggestion] Réusabilité -> Réutilisabilité

### ISSUE THREAD

**Issue by DaedalusDev** [vuejs-fr/vuejs.org#162]
Bonjour,

je ne pense pas que "Réusabilité" existe donc je le remplacerai par "Réutilisabilité".

Merci pour votre beau boulot.

**Comment by Haeresis** [comment]
Je n'y vois pas d'inconvéniant pour ma part !

**Comment by NathanBnm** [comment]
Effectivement le mot "Réusabilité" n'existe pas. Je suis d'accord avec @DaedalusDev.
Voir [https://fr.wiktionary.org/wiki/réutilisabilité](https://fr.wiktionary.org/wiki/r%C3%A9utilisabilit%C3%A9).

**Comment by Haeresis** [comment]
Tu peux nous faire une pull request @DaedalusDev ?

**Comment by sarahdayan** [comment]
C'est fait 🙂 #209
