### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#18]
Voici un extrait du fichier `src/v2/guide/single-file-components.md`

>### Qu'en est-il de la séparation des préoccupations (Separation of concerns) ?

> Une chose importante à souligner est que **la séparation des préoccupations n'est pas identique à la séparation des fichiers**.

**Separation of concerns** semble traduit majoritairement par **séparation des préoccupations** dans les traductions relative à l'informatique. Il est question ici du terme défini ainsi par [Wikipedia](https://en.wikipedia.org/wiki/Separation_of_concerns).

À noter que Wikipedia lui-même n'a pas de lien vers une traduction française.

Un problème souligné a été le suivant : le terme **préoccupation** en français inclut une dimension émotionnelle et n'est pas réellement clair sur ce qu'il signifie réellement. Des traductions alternatives sont envisagées, qu'en pensez-vous :

**Vote :**

- Garder **séparation des préoccupations** : 1
- Utiliser **séparation des rôles** : 0
- Utiliser **séparation des responsabilités** : 1

**Comment by Haeresis** [comment]
**séparation des responsabilités** c'est top !

**Comment by sylvainpolletvillard** [comment]
Je vote préoccupation, plus proche de la traduction littérale de "concern" et déjà utilisé dans d'autres présentations francophones
https://architecturead.wordpress.com/2011/07/22/separation-des-preoccupations-separation-of-concerns/
http://weblog.godlike.fr/2012/06/06/abap-bonnes-pratiques-separation-of-concerns/
http://www.itilfrance.com/index.php?pc=pages/docs/glossaire/S/terme_451.inc

Et au contraire je pense qu'il est essentiel d'indiquer le terme d'origine entre parenthèses, puisque c'est ce terme ci qui est le plus utilisé largement même au sein de la communauté francophone.
