### ISSUE TITLE
Mauvaise version stable

### ISSUE THREAD

**Issue by edimitchel** [vuejs-fr/vuejs.org#223]
Hello la team des traducteurs, déjà comment allez-vous ?
Y a-t-il besoin de soutien ? Je peux faire appel à notre communauté Strasbourgeoise pour traduire la doc en Alsacien ça vous irait ? Non plus sérieusement, si vous avez un message à faire passer, n'hésitez pas ;)

Sinon, je suis là car j'ai vu que la version de release stable sur la doc française est erronée : 
![image](https://user-images.githubusercontent.com/2922851/82138009-2e828280-981d-11ea-90a1-7805adca2dc3.png)

Je n'arrive pas à trouver dans la configuration `_config.yml` le paramètre `vue_version`..

**Comment by Haeresis** [comment]
Hello @edimitchel

Ton aide, quelle quelle soit est la bienvenue !

D'où provient ta capture d'écran ? Sur une page de la documentation FR ? Et le numéro indiqué est différent sur la page EN, c'est ça ?!

Quand je cherche les élément affiché ici, c'est le fichier `vuejs.org\db.json` qui resort.

**Comment by edimitchel** [comment]
Hello, c'est ici : https://fr.vuejs.org/v2/guide/installation.html#Notes-de-version

**Comment by Haeresis** [comment]
Merci !
