### ISSUE TITLE
Instance Vue versus Instance de Vue

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#24]
J'arrête pas de le croiser et c'est l'un des seuls moment ou il y a pas le « de ».

Vue est un nom propre. Comme Haeresis est un nom propre ou même Bruno est un nom propre. À ce sens, quand on décrit quelque chose qui m'appartient, il y a obligatoirement un « de » devant ?

« Un cheveu de Bruno », « Le blog de Haeresis », « Un sourire d'Alice », « Une instance de Vue ». Ou même encore si j'étais instanciable « Une instance de Bruno ».

Vous pouvez lire ici : « Les instances d'Object » https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object#Les_instances_d'Object_et_son_prototype

Je comprends parfaitement le terme « Une instance Vue » car j'ai l'habitude de lire « A Vue instance » mais dans les fait : 

« Un cheveu Bruno », « Le Blog Haeresis », « Un sourire Alice », ou même « Une instance Bruno » c'est pas correct ?

Est-ce que je me trompe ou est ce que je peux entamer une relecture des articles déjà traduit pour transformer « instance Vue » en « instance de Vue » ?

Dites moi !

**Comment by nyl-auster** [comment]
pour en programmation on dit l'instance **d'**un objet. Vue étant le nom de l'objet.

**Comment by sylvainpolletvillard** [comment]
ok pour toujours mettre "de" devant
