### ISSUE TITLE
[traduction en cours] - forms.md

### ISSUE THREAD

**Issue by nyl-auster** [vuejs-fr/vuejs.org#33]
_( Je tente une nouvelle approche : demander dans une issue séparée les phrases sur lesquelles je galère le plus sur la page en cours de traduction / les points les plus délicats. Le but étant d'alléger un peu la review et de bloquer moins longtemps tout seul sur les points délicats. )_

Comment traduiriez vous "**edge cases**" dans cette phrase ?

> Although a bit magical, `v-model` is essentially syntax sugar for updating data on user input events, **plus special care for some edge cases**.

**Comment by Humeira** [comment]
Cas extrêmes?

**Comment by forresst** [comment]
plus spécialement curatif dans des cas particuliers

**Comment by nyl-auster** [comment]
@forresst @Humeira cool merci pour vos suggestions. Je vais partir sur "cas particuliers" pour l'instant.

**Comment by nyl-auster** [comment]
Je bloque sur "## Value Bindings" , dans le sens "liaison de données bidirectionnelle des attributs value des input de formulaire"

Liaison des attributs value ? Liaison des valeurs ? Liaisons des value ?

**Comment by forresst** [comment]
Le plus logique pour moi :
Liaisons sur l'attribut _value_
> J'ai mis exprès _value_ en italique ou à mettre ainsi `value`

**Comment by nyl-auster** [comment]
@forresst merci pour l'avis !

**Comment by nyl-auster** [comment]
la pull request est en cours, je ferme : https://github.com/vuejs-fr/vuejs.org/pull/35
