### ISSUE TITLE
Màj : installation.md

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#36]
Le `installation.md`  a été mis à jour. Il faut faire une relecture de ce truc. Je prends.

**Comment by Haeresis** [comment]
J'ai traduis `installation.md` avec les nouveautés mais j'ai déjà un fork de `vuejs/vuejs.org` qui est bloqué pour une pull request. C'est à dire que si je fais un fork de `vuejs-fr/vuejs.org` github ne veut pas car j'ai déjà un fork de `vuejs/vuejs.org`.

Une idée ?

**Comment by Humeira** [comment]
@Haeresis Peut-être sur une nouvelle branche?

**Comment by Haeresis** [comment]
Merci @Humeira 

Je ferrais ça la prochaine fois.

Ouvrir une nouvelle branche sur mon fork de vuejs/vue.org 
Faire un fetch sur la branche que je viens de créer depuis la branche master du repo vuejs-fr/vue.org 
Merger ça

**Comment by Humeira** [comment]
@Haeresis C'est juste une suggestion. Du coup, qu'avez-vous fait?

**Comment by Haeresis** [comment]
La pull requests a été valider ce qui m'a libéré la place pour refaire un fork basé sur ce repo (plutot que celui du repo officiel) !

**Comment by Humeira** [comment]
@Haeresis Il faut peut-être faire une branche par page la prochaine fois?
c'est aussi plus simple à gérer lors des pull requests.

**Comment by Haeresis** [comment]
Oui ! C'est même sur. Une branche par fichier pour gérer chaque pull request **par** fichier !

**Comment by Haeresis** [comment]
Suite à tes remarques j'ai aménager des nouveaux proccessus pour faciliter le suivi de traduction.
