### ISSUE TITLE
Création des Chat et Forum français

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#39]
## Chat et Frorum

Je propose de créer les espaces de discussion français pour le Chat et le Forum.

## Chat

Pour le chat c'est ici : https://gitter.im/vuejs-fr/vue 

Le topic mentionne la version En (https://gitter.im/vuejs/vue) pour plus d'aide le temps que le chat se remplisse.

## Forum

Pour le forum c'est en cours de demande ici : https://forum.vuejs.org/t/create-a-france-category-for-french-discussions-helps/7468

L'url devrait être https://forum.vuejs.org/c/france

Le forum étant une sous partie du forum plus global officiel, l'accès à la partie anglaise en cas de question en suspend est facile (en attendant que le forum se popularise).

## Accès depuis https://fr.vuejs.org

Au niveau de l'accès je propose de conserver dans le menu les liens vers les plateformes anglaises mais de préciser un lien directe vers les parties avec (fr)

```html
<li><ul>
  <li><a href="http://forum.vuejs.org" class="nav-link" target="_blank">Forum</a> (<a href="https://forum.vuejs.org/c/france" class="nav-link" target="_blank">Fr</a>)</li>
  <li><a href="https://gitter.im/vuejs/vue" class="nav-link" target="_blank">Chat</a> (<a href="https://gitter.im/vuejs-js/vue" class="nav-link" target="_blank">Fr</a>)</li>
  <li><a href="https://github.com/vuejs-templates" class="nav-link" target="_blank">Templates</a></li>
</ul></li>
```

Toutes suggestions est bonne à prendre !

**Comment by nyl-auster** [comment]
Yo, bravo pour toutes les initiatives ! Ca pose aussi un peu la question de comment populariser un peu plus vuejs parmi les français.

J'ai le sentiment que contribuer sur stackoverflow serait un meilleur moyen de populariser vuejs, si je dois investir quelques minutes ce sera du coup plutôt sur stackoverflow pour ma part. Il me semble que Evan You avait twitté en ce sens d'ailleurs.

**Comment by nyl-auster** [comment]
@Haeresis PS : je parle juste concernant le forum

**Comment by Haeresis** [comment]
On peut déjà nous même clore les issues de type « discussion / question » qui n'ont pas de rapport avec la traduction en réorientant les utilisateurs vers le forum ? Pour ma part je réponds à quasiement toutes les suggestions demandé en JavaScript sur Human Coder en glissant toujours quelque part un exemple de « comment tu te serais pas pris la tête avec vue ».

En général on vient souvent avec un problème jQuery, je montre toujours que sans jQuery s'était bien souvent presque pareil (quand jQuery n'est pas justifié vis à vis de la complexité de l'exemple) et surtout que avec Vue c'était super simple !

Genre :

- Vanilla : http://codepen.io/Haeresis/pen/EWaLvO
- jQuery : http://codepen.io/Haeresis/pen/ryavOd
- Vue : http://codepen.io/Haeresis/pen/JWovjm

**Comment by nyl-auster** [comment]
@Haeresis ha bin oui, C'est sûr que Vuejs versus jQuery y'a pas à chier :D 
La "concurrence" est surtout entre React et Vuejs, mais React a occupé le terrain en premier et a su construire une communauté très active et très enthousiaste

**Comment by sylvainpolletvillard** [comment]
Je suggère d'appeler la catégorie forum "Français" ou "Francophone" plutôt que "France". Ne pas oublier qu'on a beaucoup d'amis francophones qui ne vivent pas en France: belges, suisses, québécois, et de nombreux pays africains. C'est la même raison pour laquelle on évite d'utiliser les drapeaux comme pictographie pour changer de langue.

**Comment by Haeresis** [comment]
Tu as absoluement raison

**Comment by Haeresis** [comment]
Ça a pas l'air de bouger beaucoup côté admin, si vous souhaitez vous rendre sur https://forum.vuejs.org/t/create-a-francais-category-for-french-discussions-helps/7468 pour demander à votre tour l'ouverture du forum p-e que ça pourrait faire la différence. @forresst, @nyl-auster, @gbaudoin @Teraglehn, @PierreAmmeloot ou p-e @Ti-Bretin ?

**Comment by nyl-auster** [comment]
j'ai ajouté un "+1 :D" mais il est en cours de modération xD

**Comment by Haeresis** [comment]
Point mort, je crois que tout le monde s'en fou XD...
