### ISSUE TITLE
Tutoiement vs Vouvoiement

### ISSUE THREAD

**Issue by sylvainpolletvillard** [vuejs-fr/vuejs.org#5]
Bonjour,

J'ai remarqué que le tutoiement avait été employé pour la page d'accueil:
> Tu connais HTML, CSS et JavaScript ? Lis le guide et commence à développer sans perdre de temps !

Cela m'a un peu surpris, car je trouve que cela dénote avec l'image professionnelle qu'essaie de refléter le style par sa charte graphique. Je voudrais ouvrir la débat pour savoir si l'on emploit le tutoiement et un ton informel ou le vouvoiement et un ton plus formel. 

Quoi que l'on décide, il faudra appliquer la même consigne sur toutes les pages.

**Comment by Haeresis** [comment]
Je suis partisant du « vouvoiement » pour ma part aussi 

> Vous connaissez HTML, CSS et JavaScript ? Lisez le guide et commencez à développer sans perdre de temps !

Me semble plus approprié, sérieux et respectueux.

**Comment by zyhou** [comment]
En effet, je me suis un peu enflammé avec le tutoiement, le vouvoiement fait bien plus pro et sérieux.

**Comment by sylvainpolletvillard** [comment]
Si tout le monde est d'accord, va pour le vouvoiement ! Mais vous pouvez me tutoyer :smile:
