### ISSUE TITLE
Core Team traduction

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#52]
Quelqu'un peu m'expliquer ce que signifie exactement « Core Team » ?

Pour moi le « Core » c'est l'unité principale. Donc dans ce contexte pour moi c'est l'équipe principale. Dans un projet Github, puisque tout le monde peut participer, tout le monde fait partie d'une équipe. Par exemple nous somme l'équipe de traduction française. Mais dans le cas de Vue, c'est l'équipe de personne la plus active sur le repo Vue.js ? L'équipe initialement créée ? L'équipe officiellement reconnue par l'organisation `vuejs` ? Les 3 mecs au centre de l'équipe principale qui arrache tout ?

Pour moi c'est le point 3, l'équipe officiellement reconnue par l'organisation `vuejs` composée probablement de gars depuis le début, de gars arrivés plus tard mais bien actif sur le projet bref de gars faisant « officiellement » partie de l'équipe. Pour moi une « Core Team » c'est une « équipe officielle » parce que dans « équipe de base » on a pas la notion des gens qui l'on rejoint, dans « équipe au coeur », on a pas la notion de personne satellite autour de Vue (comme le gars qui rédige le guide Officiel de Vue mais qui ne le dev pas nécessairement).

Au pire, pour moi, « coeur de l'équipe » c'est pour parler de personne dans l'équipe principale qui forme un petit noyau dur (à moins que c'est justement de ça qu'on parle ? Mais ça serait étonnant).

Pour ma part « équipe principale » est quelque chose de pas mal (ou p-e « équipe officielle » bien qu'à mon avis dans ce cas là il y aurait eut « official team » comme terme)

Vous en pensez quoi ?

**Comment by forresst** [comment]
Pour moi, la "Core Team" est l'équipe principale.
C'est à dire les personnes qui maintiennent le projet : elles ont souvent des droits supplémentaires pour gérer le projet. Si on fait la corrélation avec Github, c'est les personnes qui sont `Member`.

Avis perso ...

**Comment by Haeresis** [comment]
Du coup « Équipe Principale » pour « Core Team » est correct ?

**Comment by forresst** [comment]
Oui pou moi cela me semble correct

**Comment by sylvainpolletvillard** [comment]
Littéralement "le coeur de l'équipe", ça désigne les personnes qui travaillent en étroite collaboration, sur une base quotidienne (ou hebdomadaire max), qui échangent régulièrement, se rendent des comptes, et auxquels on confie des tâches de la roadmap.
