### ISSUE TITLE
Que pensez vous de l'outil GitLocalize

### ISSUE THREAD

**Issue by Haeresis** [vuejs-fr/vuejs.org#64]
Nous avons été invité à laisser notre avis : https://github.com/vuejs/vuejs.org/issues/933 sur l'utilisation de l'outil suivant pour nous aider dans nos processus de traduction.

L'outil en question est plus précisément présenté ici : https://github.com/vuejs/vue-ssr-docs/issues/37

**Comment by Haeresis** [comment]
Pour ma part je l'ai testé, et il est plus contraignant en ce qui va concerner l'édition de contenu.

- L'édition ce fait en HTML et plus en `.md`
- L'édition global n'est plus possible.
- Comme expliqué ici, il ne résous rien que nous n'aurions pas déjà résolu : https://github.com/vuejs/vuejs.org/issues/933#issuecomment-305959977

La bonne nouvelle, c'est que nos processus actuel pourrait fonctionné avec celui-ci s'il est adopté par d'autres team de traduction.

Je propose de garder un oeil sur l'outil.

Des avis ?

N'hésitez pas à directement les partager en anglais sur la PR original sinon je ferrais un petit récapitulatif de vos idées :)

**Comment by forresst** [comment]
J'ai déjà utilisé Crowdin et Transifex. L'avantage de ces outils c'est de ne plus gérer les mises à jours faites par l'original : cela permet de gagner du temps et de rien oublier. L'inconvénient majeur c'est qu'on ne peut pas faire ce qu'on veut (surtout des variantes selon le contexte).

D'un point de vue communautaire, cela permet aussi d'être utiliser par n'importe qui : pas besoin de connaitre git(hub) et d'avoir des outils d'édition : cela permet donc une aide plus importante de la communauté.

Conclusion : plutôt POUR

**Comment by sylvainpolletvillard** [comment]
Je n'ai pas d'avis sur l'outil ne l'ayant pas testé, mais est-ce que c'est pertinent de se poser cette question alors qu'on est déjà à ~80% d'avancement sur la traduction du site ?

**Comment by Haeresis** [comment]
Je relaye l'info, toute réflexion est pertinente.

L'outil me semble justement plus pratique pour un suivi de traduction que pour la première itération qui selon moi doit forcément passer par une traduction en masse des `.md`.

**Comment by sotayamashita** [comment]
I am engineer of GitLocalize. Any help?

**Comment by Haeresis** [comment]
Nous ré-ouvrirons le sujet si la documentation change du tout au tout. Comme évoqué plus haut. La documentation étant maintenant bien avancée, et le process de GitLocalize n'étant pas encore totalement satisfaisant : 

— https://github.com/vuejs/vuejs.org/issues/933#issuecomment-314556475

Nous ré-ouvrirons le sujet si celui-ci revient sur le devant de la scène avec les améliorations demandées !
